### ISSUE TITLE
frida.core.RPCException

### ISSUE THREAD

**Issue by mail2chensh** [ChiChou/saltedfish#13]
Device: iPhone5 (32bits)
System: iOS10.0.2 
use h3lix to jailbreak. 

target App: 钉钉（v4.6.11）

logs:
```
frida-ipa-dump git:(master) ./dump.py com.laiwang.DingTalk
[info] attaching to target
[info] decrypting module DingTalk
[info] decrypting module DTMainBasicFramework
[info] decrypting module DTSharedFramework
[info] decrypting module DTExtBasicFramework
plugin com.laiwang.DingTalk.NotificationContentExtension, pid=582
[info] decrypting module DingTalkNotificationContentExtension
[info] decrypting module DTExtBasicFramework
plugin com.laiwang.DingTalk.NotificationServiceExtension, pid=585
[info] decrypting module DingTalkNotificationServiceExtension
[info] decrypting module DTExtBasicFramework
Traceback (most recent call last):
  File "./dump.py", line 246, in <module>
    main()
  File "./dump.py", line 242, in main
    task.run()
  File "./dump.py", line 220, in run
    self.dump()
  File "./dump.py", line 159, in dump
    self.dump_with_plugins()
  File "./dump.py", line 179, in dump_with_plugins
    pid = self.script.exports.launch(identifier)
  File "/Library/Python/2.7/site-packages/frida/core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "/Library/Python/2.7/site-packages/frida/core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException
```

**Comment by ChiChou** [comment]
It is known that on iOS 10 assertd will terminate extension process in a very short time. Will resolve this

**Comment by vin-zhou** [comment]
Device: iPhone6S plus
System: 9.0.2
Jailbreak

Meet the same error.

**Comment by ChiChou** [comment]
We got a jetsam patch now
