### ISSUE TITLE
iOS 12.4 issue

### ISSUE THREAD

**Issue by alexander-pick** [ChiChou/saltedfish#19]
The tool seems to habe an issue to work on iOS 12.4, any idea what might cause it?

```
Traceback (most recent call last):
  File "dump.py", line 257, in <module>
    main()
  File "dump.py", line 253, in main
    task.run()
  File "dump.py", line 228, in run
    self.dump()
  File "dump.py", line 163, in dump
    self.dump_with_plugins()
  File "dump.py", line 183, in dump_with_plugins
    pid = self.script.exports.launch(identifier)
  File "C:\python27-x64\lib\site-packages\frida\core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "C:\python27-x64\lib\site-packages\frida\core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException: <exception str() failed>
```

**Comment by ChiChou** [comment]
rewritten everything
